/* eslint-disable */
// Generated by Wrangler by running `wrangler types workers/ingest/worker-configuration.d.ts --config workers/ingest/wrangler.jsonc --env-interface IngestEnv --include-runtime false` (hash: 65c6755eea2c09ba3fe387b40e5f18db)
interface __BaseEnv_IngestEnv {
	MEAL_PHOTOS: R2Bucket;
	DB: D1Database;
	MEAL_QUEUE: Queue;
	PUBLIC_ORIGIN: "https://calocount-ingest.example.workers.dev";
	OWNER_KEY: "default";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_IngestEnv {}
}
interface IngestEnv extends __BaseEnv_IngestEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_ORIGIN" | "OWNER_KEY">> {}
}
