/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/ingest/wrangler.jsonc --include-runtime=false --env-interface=IngestEnv workers/ingest/worker-configuration.d.ts` (hash: 17b4bbd0dd2e49b0bcfbd6cfb25e0d11)
interface __BaseEnv_IngestEnv {
	MEAL_PHOTOS: R2Bucket;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_IngestEnv {}
}
interface IngestEnv extends __BaseEnv_IngestEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, never>> {}
}
