/* eslint-disable */
// Generated by Wrangler by running `wrangler types workers/ingest/worker-configuration.d.ts --config workers/ingest/wrangler.jsonc --env-interface IngestEnv --include-runtime false` (hash: a082cb0267d44bd4850125a1c0ab5615)
interface __BaseEnv_IngestEnv {
	MEAL_PHOTOS: R2Bucket;
	DB: D1Database;
	MEAL_QUEUE: Queue;
	PUBLIC_ORIGIN: "https://calocount-ingest.hoian-embroidery.workers.dev";
	OWNER_KEY: "default";
	AI_BACKEND: "openrouter";
	OPENROUTER_MODEL: "google/gemini-3.7-flash";
	OPENROUTER_FALLBACK_MODELS: "x-ai/grok-4.6";
	OPENROUTER_HTTP_REFERER: "https://calocount-app.hoian-embroidery.workers.dev";
	OPENROUTER_APP_NAME: "Calocount";
	MAX_RETRY_ATTEMPTS: "3";
	TELEGRAM_BOT_TOKEN: string;
	OPENROUTER_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_IngestEnv {}
}
interface IngestEnv extends __BaseEnv_IngestEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_ORIGIN" | "OWNER_KEY" | "AI_BACKEND" | "OPENROUTER_MODEL" | "OPENROUTER_FALLBACK_MODELS" | "OPENROUTER_HTTP_REFERER" | "OPENROUTER_APP_NAME" | "MAX_RETRY_ATTEMPTS" | "TELEGRAM_BOT_TOKEN" | "OPENROUTER_API_KEY">> {}
}
